volumes:
  mongodb: ~

networks:
  oam-api:


services:
  app:
    environment:
      - API_ENDPOINT=http://api:4000
      - DB_URI=mongodb://mongo/oam-api
      - BROWSER_URL=http://localhost:3000
      - OAM_DEBUG=true
      - HOST=0.0.0.0
    env_file: .env.local
    build:
      context: .
      args:
        - NODE_ENV=development
    command: "false"
    networks:
      - oam-api

  api:
    extends: app
    environment:
      - PORT=4000
      - HOST_TLD=localhost
      - COOKIE_PASSWORD=12345678901234567890123456789012
      - TILER_BASE_URL=http://localhost:8000
    command: nodemon index.js
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - 4000:4000
    volumes:
      - ./bin:/app/bin
      - ./controllers:/app/controllers
      - ./models:/app/models
      - ./plugins:/app/plugins
      - ./routes:/app/routes
      - ./services:/app/services
      - ./test:/app/test
      - ./catalog-worker.js:/app/catalog-worker.js
      - ./config.js:/app/config.js
      - ./index.js:/app/index.js
      - ./newrelic.js:/app/newrelic.js
      - ./package.json:/app/package.json
      # override usage of custom mongojs driver in monq
      - ./monq/connection.js:/app/node_modules/monq/lib/connection.js:ro
      - ./monq/queue.js:/app/node_modules/monq/lib/queue.js:ro
      - ./monq/db.js:/app/node_modules/monq/lib/db.js:ro
    networks:
      - oam-api

  worker:
    extends: app
    environment:
      - DOT_ENV_FILENAME=.env.local
      - CRON_TIME=*/15 * * * *
      - PGHOST=localhost # postgres from mosaic-tiler in dev mode on localhost
      - PGPORT=5432
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=postgres
    command: nodemon catalog-worker.js
    depends_on:
      - mongo
      - register
    links:
      - mongo
      - register
    volumes:
      - ./bin:/app/bin
      - ./controllers:/app/controllers
      - ./models:/app/models
      - ./plugins:/app/plugins
      - ./routes:/app/routes
      - ./services:/app/services
      - ./test:/app/test
      - ./catalog-worker.js:/app/catalog-worker.js
      - ./config.js:/app/config.js
      - ./index.js:/app/index.js
      - ./newrelic.js:/app/newrelic.js
      - ./package.json:/app/package.json
    # This allows usage of services running directly on the host machine
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - oam-api

  transcoder:
    extends: app
    command: nodemon bin/transcoder.js
    depends_on:
      - mongo
    links:
      - api
      - mongo
    volumes:
      - ./bin:/app/bin
      - ./controllers:/app/controllers
      - ./models:/app/models
      - ./plugins:/app/plugins
      - ./routes:/app/routes
      - ./services:/app/services
      - ./test:/app/test
      - ./catalog-worker.js:/app/catalog-worker.js
      - ./config.js:/app/config.js
      - ./index.js:/app/index.js
      - ./newrelic.js:/app/newrelic.js
      - ./package.json:/app/package.json
    networks:
      - oam-api

  register:
    build:
      context: .
      args:
        - NODE_ENV=development
    command: http-server test/
    ports:
      - 8080:8080
    volumes:
      - ./test:/app/test
    networks:
      - oam-api

  mongo:
    image: mongo:6
    volumes:
      - mongodb:/data/db
    networks:
      - oam-api

  mongo-express:
    # this version works with Mongo v6
    # https://github.com/mongo-express/mongo-express/issues/887#issuecomment-1241830515
    # upgrading past this has not been tested, but probably works
    image: mongo-express:1.0
    ports:
      - 8081:8081
    links:
      - mongo
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
    networks:
      - oam-api
